version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: amplifica-api
    container_name: amplifica-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8000:8000"
    networks:
      - amplifica-network
    depends_on:
      - redis
    command: php artisan serve --host=0.0.0.0 --port=8000

  redis:
    image: redis:7-alpine
    container_name: amplifica-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - amplifica-network

networks:
  amplifica-network:
    driver: bridge

volumes:
  redis-data: